apiVersion: v1
kind: Service
metadata:
  name: counter-app
  namespace: ns-dev
spec:
  selector:
    app: counter-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080